const URL = 'https://api.bangneedu.com';
export const CLOCK = URL + '/punchTheClock';
export const ARTICLE = URL + '/article';
export const PATH = URL + '/learningPath';
export const PATH_INFO = URL + '/learningPathDetails';
export const PATH_DETAILS = URL + '/learningPathDetails/details';
export const MASTER = URL + '/projectMentor'
export const ORDER = URL + '/orderForm'
export const TaskUser = URL + '/projectTaskUser'
export const ProjectTask = URL + '/projectTask'
export const Project = URL + '/project'
export const UserInfo = URL + '/user'
export const CreateOrder = URL + '/pay/createOrder'